### ISSUE TITLE
Die Kontoerstellung ist deaktiviert

### ISSUE THREAD

**Issue by PummelWummel** [BSchleyer/redhost-panel#1]
Trotz dem neuen Update von der Datenbank File kommt der Fehler trotzdem.

Bitte um erneutes Update :)

**Comment by BSchleyer** [comment]
Ich habe gerade nochmal den INSERT bei der Datenbank gesetzt.

Bitte aus der Datenbank den INSERT INTO settings Befehl raus kopieren, dann gehst Du bei phpMyAdmin auf die Settings-Tabelle und auf SQL, dann fügst Du den INSERT Befehl ein und drückst auf "OK". Danach sollte es funktional sein.

ODER

auf Einfügen drücken, bei login und register eine 1 einfügen dann auf OK.

Andernfalls nochmal die Datenbank aus der Repository herunterladen und neu einfügen.

Sollte das nicht klappen, kannst Du mich gerne im Discord kontaktieren - dann machen wir das zusammen.
Tag: Björn Schleyer#5384
