### ISSUE TITLE
Fehler bei kostenlosen Services

### ISSUE THREAD

**Issue by ghost** [BSchleyer/redhost-panel#11]
Wenn man einen Service auf 0 € setzt also kostenlos und dann ohne Guthaben bestellen will kommt der Fehler "
Ungültige Anfrage bitte versuche es erneut (1001)"

**Comment by BSchleyer** [comment]
Das ist gewollt, da es im Live-Modus unrealistisch wäre - wenn der Preis bei 0,00€ steht. Für uns kein Issue.

**Comment by NilsJant** [comment]
Du musst in der order.php die if Abfrage auskommentieren.

```
    /* if($price <= 0){
        $error = 'Ungültige Anfrage bitte versuche es erneut (1001)';
    } */
```

Dann sollte es gehen.
