### ISSUE TITLE
Game Server erstellung

### ISSUE THREAD

**Issue by NilsJant** [BSchleyer/redhost-panel#13]
Hi, ich nur ein Game Server bestellen der auch erstellt wird. Wenn ich einen zweiten bestelle kommt folgender Fehler bei dem Cronjob:

`"{"errors":[{"code":"NoViableNodeException","status":"400","detail":"No nodes satisfying the requirements specified for automatic deployment could be found."}]}"`

So steht das auch im Debug drinnen.

**Comment by Whity07** [comment]
Schau mal in die DB

**Comment by NilsJant** [comment]
Was genau soll ich in der DB gucken?

**Comment by NilsJant** [comment]
Okay Issue hat sich erledigt. Ich musste lediglich nur den Mailserver eintragen.
