### ISSUE TITLE
Proxmox Einbindung

### ISSUE THREAD

**Issue by Diamond-Hosting** [BSchleyer/redhost-panel#20]
Hallo mit einander, ich möchte gerne meinen Proxmox Host in das Panel Integrieren so das Root Server Bestellungen getätigt werden können. Habe einen server_host_node in der Tabelle schon eingetragen und die product_option_entries auch Konfiguriert sowie mein OS hinzugefügt.

**Comment by BSchleyer** [comment]
Hallo,
die aktuelle Software ist nicht dafür ausgelegt, KVM-Server selbstständig bzw. automatisch zu betreiben. Die Anbindung für die Automatisierung liegt nur für LXC-Container vor.

Unsere Entwicklung an einer neuen Version hält leider noch ziemlich lange an, entsprechend können wir unser Update - in dem eine Proxmox-Automatisierung eingebunden ist - noch nicht präsentieren. Jedoch kannst Du uns, der Schleyer-EDV, einen Auftrag stellen. Dann entwickeln wir das Modul in dein bestehendes Panel.

Grüße aus Gelsenkirchen.
