### ISSUE TITLE
Call to a member function protect() on null

### ISSUE THREAD

**Issue by Shvquu** [BSchleyer/redhost-panel#22]
![Bild_2024-05-21_212240745](https://github.com/BSchleyer/redhost-panel/assets/70787619/092e9283-514c-495f-bb89-b0e79c06916d)

**Comment by BSchleyer** [comment]
Looks like the wrong PHP version to me. Which one has been set or is being used?

Currently it only runs on PHP7.4.

**Comment by Shvquu** [comment]
my plesk is telling me that the composer things only at version at 8.0 working

**Comment by Shvquu** [comment]
Diesen Fehler bekomme ich auch nun nachdem ich das Panel versucht habe neu zu installieren

`AH01071: Got error 'PHP message: PHP Fatal error: Uncaught Error: Class 'Dotenv\\Dotenv' not found in [/var/www/vhosts/panel.hosthorizon.de/httpdocs/app/Kernel.php](https://h1016376.serverkompetenz.net:8443/smb/file-manager/code-editor?currentDir=%2Fhttpdocs%2Fapp&subscriptionId=44&file=Kernel.php&redirect=%2Fsmb%2Flog-file%2Fbrowser%2Fid%2F44):9\nStack trace:\n#0 [/var/www/vhosts/panel.hosthorizon.de/httpdocs/public/index.php](https://h1016376.serverkompetenz.net:8443/smb/file-manager/code-editor?currentDir=%2Fhttpdocs%2Fpublic&subscriptionId=44&file=index.php&redirect=%2Fsmb%2Flog-file%2Fbrowser%2Fid%2F44)(12): include_once()\n#1 {main}\n thrown in [/var/www/vhosts/panel.hosthorizon.de/httpdocs/app/Kernel.php](https://h1016376.serverkompetenz.net:8443/smb/file-manager/code-editor?currentDir=%2Fhttpdocs%2Fapp&subscriptionId=44&file=Kernel.php&redirect=%2Fsmb%2Flog-file%2Fbrowser%2Fid%2F44) on line 9'`

**Comment by xeaa** [comment]
@Shvquu hast du alle Composer Dependencies installiert? Probier mal `composer install` in der Console auszuführen. Sollte das nicht funktionieren übernimm die composer.json Datei aus GitHub ohne Änderungen in dein Projekt und probiere es neu zu installieren.
