### ISSUE TITLE
"Discord_ID" Funktion

### ISSUE THREAD

**Issue by Kaseax** [BSchleyer/redhost-panel#5]
Hey, wo genau kann man für seinen Account die discord_id hinzufügen? Das einzigste, was ich gefunden habe, war das dazu etwas im resources/api/ Ordner ist.

**Comment by BSchleyer** [comment]
Die Discord-ID kannst Du in der Datenbank setzen.

Hierfür auf die User-Tabelle klicken und dort die discord_id suchen, dann setzen.

**Comment by Kaseax** [comment]
Das ist mir bewusst, aber wo kann der Kunde diese setzen?

**Comment by BSchleyer** [comment]
Der Kunde kann selbst keine Discord-ID setzen, dafür müsste das Panel entweder weiterentwickelt werden oder die API genutzt werden.

Die API kann bspw. mit einem Discord-Bot angesteuert werden oder selbst über eigene Funktionen im Portal (wäre eine Weiterentwicklung).

So gebe es keine anderen Möglichkeiten.

**Comment by Kaseax** [comment]
Okay, und wie kann man die API dann "ansteuern"?

**Comment by dariusaurich** [comment]
@Unerheblich dabei könnte ich im notfall helfen denke ich
DC: Darius W.#9744
