### ISSUE TITLE
renewSupportPin

### ISSUE THREAD

**Issue by feeeedox** [BSchleyer/redhost-panel#7]
Moin, nach der Registrierung kommt ein Whitescreen durch die Function `renewSupportPin`

Hier die Function:
![image](https://user-images.githubusercontent.com/67076970/167320564-9f93b477-a370-4904-a41a-c01cd837ef12.png)

Und nach dem Login krieg ich auch einen Whitescreen dort liegt es an der `generateSessionToken` Function:
![image](https://user-images.githubusercontent.com/67076970/167320587-f5d9e7ab-1d95-4aa2-8cdd-e9fb29d3ef1e.png)

**Comment by Kaseax** [comment]
Am besten stellst du mal in der .env den Debug ein. Dann sollte ein genauerer Fehler kommen. Hatte das ganze auch schonmal, müsste anhand des Fehlers nur mal schauen was das Problem war.

**Comment by BSchleyer** [comment]
Tach,
sorry, bin momentan viel unterwegs und verfolge keine GitHub-Notifys. Das Panel hat bei einigen und mir keinen Fehler bei dem Auth-Modul erzeugt.

Bitte beschreibt den Fehler genauer, dass man sich das genauer anschauen kann. :)

**Comment by bastianleicht** [comment]
Moin, das liegt an dem 
```php
helper::generateRandomString();
```
Helper kann hier nicht Statisch abgerufen werden. Mit
```php
(new Helper)->generateRandomString()
```
sollte alles funktionieren.

**Comment by BSchleyer** [comment]
Habe ich mal commited.
