### ISSUE TITLE
Email Funktion sendet keine Emails

### ISSUE THREAD

**Issue by GreenPepperYT** [BSchleyer/redhost-panel#9]
Hey. Ich habe bei meinem Webspace die integrierte Email Funktion mit RoundCube eingerichtet. Die Emails selbst senden bei manueller nutzung auch und kommen einwandfrei an. 
Jetzt habe ich die Daten im app/notifications/sendMail.php eingetragen jedoch senden keine Emails.
```      $mail->SMTPDebug = 0;
        $mail->isSMTP();
        $mail->SMTPAuth = true;
        $mail->Host = 'domain.de';
        $mail->SMTPSecure = 'ssl';
        $mail->SMTPAutoTLS = true;
        $mail->Username = 'no-reply@domain.de';
        $mail->Password = 'password';
        $mail->Port = 587;```

**Comment by dariusaurich** [comment]
schau mal auf deinen port ^^
TIPP: Für plesk meist: 465

**Comment by GreenPepperYT** [comment]
selbst mit Port 465 kommt keine Email an..

**Comment by BSchleyer** [comment]
Schreib mir mal im Discord, dann schauen wir bestenfalls gemeinsam mal darüber. :)

**Comment by GreenPepperYT** [comment]
Habe dir geschrieben, du antwortest nur leider nicht :/

**Comment by dariusaurich** [comment]
Probiere mal Port 25

**Comment by GreenPepperYT** [comment]
Nope, kommt immer noch nix.

**Comment by BSchleyer** [comment]
Problem wurde bereits identifiziert und liegt demnach nicht an dem Panel.
